### PR TITLE
Fix the installation on Mac OS X.

### PR DESCRIPTION
**Pull request by lazywei**
Fix the building process on Mac OS X. Please refers to the commit message of e78352e for details.
Also, I added `requirements.txt` for simplifying the requirements installation.

Please feel free to let me know if you have any concern regarding to this PR.

Thanks.

### CODE REVIEW

**Comment by lsc36** [comment]
Looks nice. Ping @yangarbiter 

What's `.ropeproject` in gitignore though?

**Comment by lazywei** [comment]
Hmm... it's generated by my Vim & Rope, which is a coding style checking
library: https://github.com/python-rope/rope.
If we're not using Rope, I can rebase the commit and remove this line.

Thanks.

SC Lee <notifications@github.com> 於 2015年12月9日 週三 下午7:53寫道：

> Looks nice. Ping @yangarbiter <https://github.com/yangarbiter>
>
> What's .ropeproject in gitignore though?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lsc36/libact/pull/5#issuecomment-163199946>.
>
-- 
Chih-Wei (Bert)

**Comment by yangarbiter** [comment]
Looks nice! Though I don't have a Mac OS X to test it, but it seems okey for me to merge.

**Comment by lsc36** [comment]
Remove the `.ropeproject` and I'll merge this. Thanks.

**Comment by lazywei** [comment]
Done.

**Pull request merged**
